using Starfield_DataManagement.Data;
using Starfield_DataManagement.Properties;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Starfield_DataManagement
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private DataManager dataManager;

        public MainWindow()
        {
            // check settings upgrade to new application version
            if (Settings.Default.Upgraded)
            {
                Settings.Default.Upgrade(); // upgrade the settings from last version to new version, adjust settings to current version
                Settings.Default.Upgraded = false; // don't upgrade again until new application version
            }

            InitializeComponent();

            dataManager = (DataManager)Resources["SFDataManager"];


        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            DataGrid dg = (DataGrid)sender;

            foreach(DataGridColumn column in dg.Columns)
            {
                if(!(column.Header.ToString() is "Id" or "Level" or "Star" or "Planet" or "Moon"))
                {
                    column.Visibility = Visibility.Collapsed;
                }
            }
        }

        private void Star_DataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            Settings.Default.SelectedStar.Clear();
            Settings.Default.SelectedStar.AddRange(dataManager.GetStarList((System.Data.DataRow[])e.AddedItems));

        }

        private void Planet_DataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            Settings.Default.SelectedPlanet.Clear();
            Settings.Default.SelectedPlanet.AddRange(dataManager.GetPlanetList((System.Data.DataRow[])e.AddedItems));

        }

        private void Moon_DataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            Settings.Default.SelectedMoon.Clear();
            Settings.Default.SelectedMoon.AddRange(dataManager.GetMoonList((System.Data.DataRow[])e.AddedItems));

        }


    }
}
